%YAML:1.0
imu:
  # inertial sensor noise model parameters (static)
  # gyroscope_noise_density: 0.1       # [ rad / s / sqrt(Hz) ]
  # gyroscope_random_walk: 0.001       # [ rad / s^2 / sqrt(Hz) ]
  # accelerometer_noise_density: 1    # [ m / s^2 / sqrt(Hz) ]
  # accelerometer_random_walk: 0.01    # [ m / s^3 / sqrt(Hz) ]
  # accelerometer_bias: [0.0, 0.0, 0.0] # acc bias prior
  # gyroscope_bias: [0.0, 0.0, 0.0]     # gyro bias prior
  extrinsic:
    q_bi: [ 0.0, 0.0, 0.0, 1.0 ] # x y z w
    p_bi: [ 0.0, 0.0, 0.0 ] # x y z [m]
  noise:
    cov_g: [
      0.05, 0.0, 0.0,
      0.0, 0.05, 0.0,
      0.0, 0.0, 0.05]
    cov_a: [
      0.2, 0.0, 0.0,
      0.0, 0.2, 0.0,
      0.0, 0.0, 0.2]
    cov_bg: [
      4.0e-5, 0.0, 0.0,
      0.0, 4.0e-5, 0.0,
       0.0, 0.0, 4.0e-5]
    cov_ba: [
      0.02, 0.0, 0.0,
      0.0, 0.02, 0.0,
       0.0, 0.0, 0.02]

cam0:
  # camera0 wrt. body frame
  # T_BS:
  #   cols: 4
  #   rows: 4
  #   data: [1.0, 0.0, 0.0, 0.005,
  #          0.0, 1.0, 0.0, 0.005,
  #          0.0, 0.0, 1.0, -0.0117,
  #          0.0, 0.0, 0.0, 1.0]
  resolution: [640, 480]        # resolution of camera
  camera_model: pinhole         # camera model
  distortion_model: radtan      # distortion model
  intrinsics: [385.7544860839844, 385.7544860839844, 323.1204833984375, 236.7432098388672] # fu, fv, cu, cv
  camera_distortion_flag: 0     # use distortion model or not
  distortion: [0, 0, 0, 0] # k1, k2, p1, p2, xi
  camera_readout_time: 0.0      # camera readout time
  time_offset: 0.0              # camera time delay wrt. IMU
  extrinsic:
    q_bc: [ 0.0,  0.0, 0.0, 1.0 ] # x y z w
    p_bc: [ 0.005, 0.005, -0.0117] # x y z [m]
  noise: [
    0.5, 0.0,
    0.0, 0.5] # [pixel^2]
